/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitesRouteImport } from './routes/invites'
import { Route as DrivesRouteImport } from './routes/drives'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIdRouteImport } from './routes/results.$id'
import { Route as DrivesIdRouteImport } from './routes/drives.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitesRoute = InvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const DrivesRoute = DrivesRouteImport.update({
  id: '/drives',
  path: '/drives',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResultsRoute,
} as any)
const DrivesIdRoute = DrivesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DrivesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRouteWithChildren
  '/invites': typeof InvitesRoute
  '/login': typeof LoginRoute
  '/questions': typeof QuestionsRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/drives/$id': typeof DrivesIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRouteWithChildren
  '/invites': typeof InvitesRoute
  '/login': typeof LoginRoute
  '/questions': typeof QuestionsRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/drives/$id': typeof DrivesIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/drives': typeof DrivesRouteWithChildren
  '/invites': typeof InvitesRoute
  '/login': typeof LoginRoute
  '/questions': typeof QuestionsRoute
  '/reports': typeof ReportsRoute
  '/results': typeof ResultsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/drives/$id': typeof DrivesIdRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/drives'
    | '/invites'
    | '/login'
    | '/questions'
    | '/reports'
    | '/results'
    | '/settings'
    | '/drives/$id'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/drives'
    | '/invites'
    | '/login'
    | '/questions'
    | '/reports'
    | '/results'
    | '/settings'
    | '/drives/$id'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/drives'
    | '/invites'
    | '/login'
    | '/questions'
    | '/reports'
    | '/results'
    | '/settings'
    | '/drives/$id'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DrivesRoute: typeof DrivesRouteWithChildren
  InvitesRoute: typeof InvitesRoute
  LoginRoute: typeof LoginRoute
  QuestionsRoute: typeof QuestionsRoute
  ReportsRoute: typeof ReportsRoute
  ResultsRoute: typeof ResultsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invites': {
      id: '/invites'
      path: '/invites'
      fullPath: '/invites'
      preLoaderRoute: typeof InvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drives': {
      id: '/drives'
      path: '/drives'
      fullPath: '/drives'
      preLoaderRoute: typeof DrivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/drives/$id': {
      id: '/drives/$id'
      path: '/$id'
      fullPath: '/drives/$id'
      preLoaderRoute: typeof DrivesIdRouteImport
      parentRoute: typeof DrivesRoute
    }
  }
}

interface DrivesRouteChildren {
  DrivesIdRoute: typeof DrivesIdRoute
}

const DrivesRouteChildren: DrivesRouteChildren = {
  DrivesIdRoute: DrivesIdRoute,
}

const DrivesRouteWithChildren =
  DrivesRoute._addFileChildren(DrivesRouteChildren)

interface ResultsRouteChildren {
  ResultsIdRoute: typeof ResultsIdRoute
}

const ResultsRouteChildren: ResultsRouteChildren = {
  ResultsIdRoute: ResultsIdRoute,
}

const ResultsRouteWithChildren =
  ResultsRoute._addFileChildren(ResultsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DrivesRoute: DrivesRouteWithChildren,
  InvitesRoute: InvitesRoute,
  LoginRoute: LoginRoute,
  QuestionsRoute: QuestionsRoute,
  ReportsRoute: ReportsRoute,
  ResultsRoute: ResultsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
